version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: semiannually
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: semiannually
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci)"
    groups:
      docker-actions:
        patterns:
          - "docker/*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: yearly
      day: monday
    commit-message:
      prefix: "chore(docker)"
